apiVersion: v1
kind: Service
metadata:
  name: diagnostics-service
  namespace: autosecureops
  labels:
    app: diagnostics-service
spec:
  selector:
    app: diagnostics-service
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
