apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: autosecureops
  labels:
    app: telemetry-service
spec:
  selector:
    app: telemetry-service
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
